/*
    Klasy: cwiczenia,
             komputerowe,
             wyklad,
             laby,
             zdalnie,
*/

let plan_parzysty = [
    [
        // PONIEDZIAŁEK
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['BDwSPr', 'A336', 'wyklad', 'J. Habel'],
        ['BDwSPr', 'A336', 'wyklad', 'J. Habel'],
        ['', '', '', ''],
        ['', '', '', ''],
        ['PrCADCAM', 'C208', 'komputerowe', 'A. Stwora'],
        ['PrCADCAM', 'C208', 'komputerowe', 'A. Stwora'],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
    ],
    [
        // WTOREK
        ['', '', '', ''],
        ['', '', '', ''],
        ['Semdypl', 'A331', 'wyklad', 'J. Zając'],
        ['Semdypl', 'A331', 'wyklad', 'J. Zając'],
        ['ProgElUS', 'A124', 'wyklad', 'K. Wójcik'],
        ['ProgElUS', 'A124', 'wyklad', 'K. Wójcik'],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['Negocj', 'A409', 'cwiczenia', 'A. Iwaszczuk'],
        ['Negocj', 'A409', 'cwiczenia', 'A. Iwaszczuk'],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
    ],
    [
        // ŚRODA
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
    ],
    [
        // CZWARTEK
        ['', '', '', ''],
        ['', '', '', ''],
        ['Prog oir', 'E07', 'laby', 'S. Krenich'],
        ['Prog oir', 'E07', 'laby', 'S. Krenich'],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['ElSzIRob', 'A124', 'wyklad', 'dr inż. Stanisław Piotr Krenich '],
        ['ElSzIRob', 'A124', 'wyklad', 'dr inż. Stanisław Piotr Krenich '],
        ['', '', '', ''],
        ['', '', '', ''],
        ['SocPsychP', 'A331', 'cwiczenia', 'J.Jaśtal'],
        ['SocPsychP', 'A331', 'cwiczenia', 'J.Jaśtal'],
        ['', '', '', ''],
        ['', '', '', ''],
    ],
    [
        // PIĄTEK
        ['SteriAuM', 'A123', 'wyklad', 'dr inż. Janusz Piotr Pobędza , prof. PK '],
        ['SteriAuM', 'A123', 'wyklad', 'dr inż. Janusz Piotr Pobędza , prof. PK '],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['ElSzIRob', 'E07', 'projekt', 'P. Łubiarz'],
        ['ElSzIRob', 'E07', 'projekt', 'P. Łubiarz'],
        ['RMWsFCzł', 'J117', 'laby', 'M.Maniowski'],
        ['RMWsFCzł', 'J117', 'laby', 'M.Maniowski'],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
    ],
];

let plan_nieparzysty = [
    [
        // PONIEDZIAŁEK
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['PodsNiez', 'J212.2', 'projekt', 'G. Kaczor'],
        ['PodsNiez', 'J212.2', 'projekt', 'G. Kaczor'],
        ['BDwSPr', 'C206', 'komputerowe', 'J.Habel'],
        ['BDwSPr', 'C206', 'komputerowe', 'J.Habel'],
        ['PrCADCAM', 'C208', 'komputerowe', 'A. Stwora'],
        ['PrCADCAM', 'C208', 'komputerowe', 'A. Stwora'],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
    ],
    [
        // WTOREK
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['WBadNauk', 'A331', 'wyklad', 'J. Zając'],
        ['WBadNauk', 'A331', 'wyklad', 'J. Zając'],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['Negocj', 'C04', 'wyklad', 'A. Iwaszczuk '],
        ['Negocj', 'C04', 'wyklad', 'A. Iwaszczuk '],
        ['', '', '', ''],
        ['', '', '', ''],
    ],
    [
        // ŚRODA
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['PodsNiez', 'C04', 'wyklad', 'dr hab. inż. Stanisław Jan Młynarski , prof. PK '],
        ['PodsNiez', 'C04', 'wyklad', 'dr hab. inż. Stanisław Jan Młynarski , prof. PK '],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
    ],
    [
        // CZWARTEK
        ['', '', '', ''],
        ['', '', '', ''],
        ['ProgElUS', 'A303', 'laby', 'P. Łubiarz'],
        ['ProgElUS', 'A303', 'laby', 'P. Łubiarz'],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['Prog Ob', 'A502', 'wyklad', 'K. Wójcik'],
        ['Prog Ob', 'A502', 'wyklad', 'K. Wójcik'],
        ['Prog Ob', 'A303', 'komputerowe', 'K.Wójcik'],
        ['Prog Ob', 'A303', 'komputerowe', 'K.Wójcik'],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
    ],
    [
        // PIĄTEK
        ['SteriAuM', 'A123', 'wyklad', 'dr inż. Janusz Piotr Pobędza , prof. PK '],
        ['SteriAuM', 'A123', 'wyklad', 'dr inż. Janusz Piotr Pobędza , prof. PK '],
        ['RMWspFCzł', 'A124', 'wyklad', 'dr hab. inż. Aleksander Kuranowski , prof. PK '],
        ['RMWspFCzł', 'A124', 'wyklad', 'dr hab. inż. Aleksander Kuranowski , prof. PK '],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['SteriAuM', 'A338', 'komputerowe', 'S.Chwastek'],
        ['SteriAuM', 'A338', 'komputerowe', 'S.Chwastek'],
        ['Prog oir', 'zdalnie', 'wyklad', 'S.Krenich'],
        ['Prog oir', 'zdalnie', 'wyklad', 'S.Krenich'],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
    ],
];
