/*
    Klasy: cwiczenia,
             komputerowe,
             wyklad,
             laby,
             zdalnie,
*/

let plan_parzysty = [
    [
        // PONIEDZIAŁEK
        ['', '', '', ''],
        ['', '', '', ''],
        ['EUSRob', 'A123', 'wyklad', 'dr inż. Marta Góra-Maniowska'],
        ['EUSRob', 'A123', 'wyklad', 'dr inż. Marta Góra-Maniowska'],
        ['EUSRob', 'A123', 'wyklad', 'dr inż. Marta Góra-Maniowska'],
        ['Ekonprz', 'G18', 'wyklad', 'mgr inż. Elżbieta Malec'],
        ['Ekonprz', 'G18', 'wyklad', 'mgr inż. Elżbieta Malec'],
        ['Ekonprz', 'G18', 'wyklad', 'mgr inż. Elżbieta Malec'],
        ['SPC', 'A303', 'komputerowe', 'dr inż. Adam Słota, prof. PK'],
        ['SPC', 'A303', 'komputerowe', 'dr inż. Adam Słota, prof. PK'],
        ['MetrSpGW', 'C01', 'laby', 'mgr inż. Izabela Sanetra'],
        ['MetrSpGW', 'C01', 'laby', 'mgr inż. Izabela Sanetra'],
        ['MikroAut', 'A302', 'komputerowe', 'mgr inż. Piotr Łubiarz'],
        ['MikroAut', 'A302', 'komputerowe', 'mgr inż. Piotr Łubiarz'],
        ['', '', '', ''],
        ['', '', '', ''],
    ],
    [
        // WTOREK
        ['ModMMCAD', 'A303', 'projekt', 'dr inż. Adam Słota, prof. PK'],
        ['ModMMCAD', 'A303', 'projekt', 'dr inż. Adam Słota, prof. PK'],
        ['ProPTech', 'C206', 'projekt', 'dr hab. inż. Jan Duda, prof. PK'],
        ['ProPTech', 'C206', 'projekt', 'dr hab. inż. Jan Duda, prof. PK'],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['Angielski', 'A531', 'cwiczenia', 'mgr Dorota Gawryła'],
        ['Angielski', 'A531', 'cwiczenia', 'mgr Dorota Gawryła'],
        ['', '', '', ''],
        ['', '', '', ''],
    ],
    [
        // ŚRODA
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['SterP4', 'A302', 'komputerowe', 'mgr inż. Piotr Łubiarz'],
        ['SterP4', 'A302', 'komputerowe', 'mgr inż. Piotr Łubiarz'],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['SterP4', 'zdalnie', 'wyklad', 'dr inż. Waldemar Paweł Małopolski'],
        ['SterP4', 'zdalnie', 'wyklad', 'dr inż. Waldemar Paweł Małopolski'],
    ],
    [
        // CZWARTEK
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['Ekonprz', 'C212', 'cwiczenia', 'mgr inż. Elżbieta Malec'],
        ['Ekonprz', 'C212', 'cwiczenia', 'mgr inż. Elżbieta Malec'],
        ['Ekonprz', 'C212', 'cwiczenia', 'mgr inż. Elżbieta Malec'],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['MetrSpGW', 'A124', 'wyklad', 'dr hab. inż. Adam Jakub Gąska, prof. PK'],
        ['MetrSpGW', 'A124', 'wyklad', 'dr hab. inż. Adam Jakub Gąska, prof. PK'],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
    ],
    [
        // PIĄTEK
        ['PodEkspl', 'G18', 'wyklad', 'dr hab. inż. Grzegorz Zając, prof. PK'],
        ['PodEkspl', 'G18', 'wyklad', 'dr hab. inż. Grzegorz Zając, prof. PK'],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['EUSRob', 'A302', 'projekt', 'dr inż. Marta Góra-Maniowska'],
        ['EUSRob', 'A302', 'projekt', 'dr inż. Marta Góra-Maniowska'],
        ['EUSRob', 'A302', 'projekt', 'dr inż. Marta Góra-Maniowska'],
        ['SPC', 'A123', 'wyklad', 'dr inż. Adam Słota, prof. PK'],
        ['SPC', 'A123', 'wyklad', 'dr inż. Adam Słota, prof. PK'],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
    ],
];

let plan_nieparzysty = [
    [
        // PONIEDZIAŁEK
        ['', '', '', ''],
        ['', '', '', ''],
        ['EUSRob', 'A123', 'wyklad', 'dr inż. Marta Góra-Maniowska'],
        ['EUSRob', 'A123', 'wyklad', 'dr inż. Marta Góra-Maniowska'],
        ['EUSRob', 'A123', 'wyklad', 'dr inż. Marta Góra-Maniowska'],
        ['', '', '', ''],
        ['PodEkspl', 'J30', 'laby', 'dr hab. inż. Grzegorz Zając, prof. PK'],
        ['PodEkspl', 'J30', 'laby', 'dr hab. inż. Grzegorz Zając, prof. PK'],
        ['', '', '', ''],
        ['', '', '', ''],
        ['MetrSpGW', 'C01', 'laby', 'mgr inż. Izabela Sanetra'],
        ['MetrSpGW', 'C01', 'laby', 'mgr inż. Izabela Sanetra'],
        ['MikroAut', 'A302', 'komputerowe', 'mgr inż. Piotr Łubiarz'],
        ['MikroAut', 'A302', 'komputerowe', 'mgr inż. Piotr Łubiarz'],
        ['', '', '', ''],
        ['', '', '', ''],
    ],
    [
        // WTOREK
        ['ModMMCAD', 'A303', 'projekt', 'dr inż. Adam Słota, prof. PK'],
        ['ModMMCAD', 'A303', 'projekt', 'dr inż. Adam Słota, prof. PK'],
        ['MetrSpGW', 'C206', 'projekt', 'dr inż. Marcin Józef Krawczyk, prof. PK'],
        ['MetrSpGW', 'C206', 'projekt', 'dr inż. Marcin Józef Krawczyk, prof. PK'],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['MikroAut', 'A303', 'projekt', 'mgr inż. Piotr Łubiarz'],
        ['MikroAut', 'A303', 'projekt', 'mgr inż. Piotr Łubiarz'],
        ['', '', '', ''],
        ['', '', '', ''],
        ['Angielski', 'A531', 'cwiczenia', 'mgr Dorota Gawryła'],
        ['Angielski', 'A531', 'cwiczenia', 'mgr Dorota Gawryła'],
        ['', '', '', ''],
        ['', '', '', ''],
    ],
    [
        // ŚRODA
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['SterP4', 'A302', 'komputerowe', 'mgr inż. Piotr Łubiarz'],
        ['SterP4', 'A302', 'komputerowe', 'mgr inż. Piotr Łubiarz'],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
    ],
    [
        // CZWARTEK
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['ProjPTech', 'A123', 'wyklad', 'dr hab. inż. Jan Duda, prof. PK'],
        ['ProjPTech', 'A123', 'wyklad', 'dr hab. inż. Jan Duda, prof. PK'],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['MikroAut', 'A123', 'wyklad', 'dr inż. Krzysztof Edward Wójcik'],
        ['MikroAut', 'A123', 'wyklad', 'dr inż. Krzysztof Edward Wójcik'],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
    ],
    [
        // PIĄTEK
        ['', '', '', ''],
        ['', '', '', ''],
        ['SPC', 'A302', 'laby', 'dr inż. Adam Słota, prof. PK'],
        ['SPC', 'A302', 'laby', 'dr inż. Adam Słota, prof. PK'],
        ['SterNhip', 'B08', 'laby', 'dr inż. Paweł Michał Walczak'],
        ['SterNhip', 'B08', 'laby', 'dr inż. Paweł Michał Walczak'],
        ['', '', '', ''],
        ['', '', '', ''],
        ['SPC', 'A123', 'wyklad', 'dr inż. Adam Słota, prof. PK'],
        ['SPC', 'A123', 'wyklad', 'dr inż. Adam Słota, prof. PK'],
        ['Ster nhip', 'A123', 'wyklad', 'dr inż. Janusz Piotr Pobędza , prof. PK'],
        ['Ster nhip', 'A123', 'wyklad', 'dr inż. Janusz Piotr Pobędza , prof. PK'],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
    ],
];
