/*
    Klasy: cwiczenia,
             komputerowe,
             wyklad,
             laby,
             zdalnie,
*/

let plan_parzysty = [
    [
        // PONIEDZIAŁEK
        ['', '', '', ''],
        ['', '', '', ''],
        ['EUSRob', 'A123', 'wyklad', 'dr inż. Marta Góra-Maniowska'],
        ['EUSRob', 'A123', 'wyklad', 'dr inż. Marta Góra-Maniowska'],
        ['EUSRob', 'A123', 'wyklad', 'dr inż. Marta Góra-Maniowska'],
        ['Ekonprz', 'G18', 'wyklad', ''],
        ['Ekonprz', 'G18', 'wyklad', ''],
        ['Ekonprz', 'G18', 'wyklad', ''],
        ['SPC', 'A303', 'komputerowe', ''],
        ['SPC', 'A303', 'komputerowe', ''],
        ['MetrSpGW', 'C01', 'laby', ''],
        ['MetrSpGW', 'C01', 'laby', ''],
        ['MikroAut', 'A302', 'komputerowe', ''],
        ['MikroAut', 'A302', 'komputerowe', ''],
        ['', '', '', ''],
        ['', '', '', ''],
    ],
    [
        // WTOREK
        ['ModMMCAD', 'A303', 'projekt', ''],
        ['ModMMCAD', 'A303', 'projekt', ''],
        ['ProPTech', 'C206', 'projekt', ''],
        ['ProPTech', 'C206', 'projekt', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
    ],
    [
        // ŚRODA
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['SterP4', 'A302', 'komputerowe', ''],
        ['SterP4', 'A302', 'komputerowe', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['SterP4', 'zdalnie', 'wyklad', ''],
        ['SterP4', 'zdalnie', 'wyklad', ''],
    ],
    [
        // CZWARTEK
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['Ekonprz', 'C212', 'cwiczenia', ''],
        ['Ekonprz', 'C212', 'cwiczenia', ''],
        ['Ekonprz', 'C212', 'cwiczenia', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['MetrSpGW', 'A124', 'wyklad', ''],
        ['MetrSpGW', 'A124', 'wyklad', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
    ],
    [
        // PIĄTEK
        ['PodEkspl', 'G18', 'wyklad', ''],
        ['PodEkspl', 'G18', 'wyklad', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['EUSRob', 'A302', 'projekt', ''],
        ['EUSRob', 'A302', 'projekt', ''],
        ['EUSRob', 'A302', 'projekt', ''],
        ['SPC', 'A123', 'wyklad', ''],
        ['SPC', 'A123', 'wyklad', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
    ],
];

let plan_nieparzysty = [
    [
        // PONIEDZIAŁEK
        ['', '', '', ''],
        ['', '', '', ''],
        ['EUSRob', 'A123', 'wyklad', 'dr inż. Marta Góra-Maniowska'],
        ['EUSRob', 'A123', 'wyklad', 'dr inż. Marta Góra-Maniowska'],
        ['EUSRob', 'A123', 'wyklad', 'dr inż. Marta Góra-Maniowska'],
        ['', '', '', ''],
        ['PodEkspl', 'J30', 'laby', ''],
        ['PodEkspl', 'J30', 'laby', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['MetrSpGW', 'C01', 'laby', ''],
        ['MetrSpGW', 'C01', 'laby', ''],
        ['MikroAut', 'A302', 'komputerowe', ''],
        ['MikroAut', 'A302', 'komputerowe', ''],
        ['', '', '', ''],
        ['', '', '', ''],
    ],
    [
        // WTOREK
        ['ModMMCAD', 'A303', 'projekt', ''],
        ['ModMMCAD', 'A303', 'projekt', ''],
        ['MetrSpGW', 'C206', 'projekt', ''],
        ['MetrSpGW', 'C206', 'projekt', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['MikroAut', 'A303', 'projekt', ''],
        ['MikroAut', 'A303', 'projekt', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
    ],
    [
        // ŚRODA
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['SterP4', 'A302', 'komputerowe', ''],
        ['SterP4', 'A302', 'komputerowe', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
    ],
    [
        // CZWARTEK
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['ProjPTech', 'A123', 'wyklad', ''],
        ['ProjPTech', 'A123', 'wyklad', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['MikroAut', 'A123', 'wyklad', ''],
        ['MikroAut', 'A123', 'wyklad', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
    ],
    [
        // PIĄTEK
        ['', '', '', ''],
        ['', '', '', ''],
        ['SPC', 'A302', 'laby', ''],
        ['SPC', 'A302', 'laby', ''],
        ['SterNhip', 'B08', 'laby', ''],
        ['SterNhip', 'B08', 'laby', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['SPC', 'A123', 'wyklad', ''],
        ['SPC', 'A123', 'wyklad', ''],
        ['Ster nhip', 'A123', 'wyklad', ''],
        ['Ster nhip', 'A123', 'wyklad', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', ''],
    ],
];
